### PR TITLE
[WIP] Add a way to create scopes with a single lifetime

### PR DESCRIPTION
**Pull request by Zoxc**
cc @cuviper @nikomatsakis

### CODE REVIEW

**Comment by cuviper** [comment]
I don't understand what you would use this for.

**Comment by Zoxc** [comment]
This avoids the need to use 2 lifetimes in order to use Rayon scopes. You just need one.

**Comment by cuviper** [comment]
Oh, like you're storing the `&Scope` somewhere, so you don't want the extra `&` lifetime?

**Comment by Zoxc** [comment]
Yeah.

**Pull request closed without merging**
