### PR TITLE
Make the TLV public and a pointer for provenance reasons

### PR DESCRIPTION
**Pull request by Zoxc**
Making the TLV public simplifies the conditional logic in `rustc`. It also uses the new faster `const` thread locals.

### CODE REVIEW

**Comment by cuviper** [comment]
Do you have a rustc branch to show the improvement there?

**Comment by Zoxc** [comment]
Not yet.

**Comment by cuviper** [comment]
Hmm, I see how this makes it easier for `#[cfg(parallel_compiler)]` or `not()`, but I think it moves even farther away from an API that we would want to add to `rayon` proper. It's ok for now in the fork though.

I recently released new versions of `rayon` and `rayon-core` -- maybe now would be a good time to rebase this fork?

**Comment by Zoxc** [comment]
> I recently released new versions of `rayon` and `rayon-core` -- maybe now would be a good time to rebase this fork?

Sure. Are you volunteering me?

**Comment by cuviper** [comment]
It was a suggestion to gauge interest, especially since you've expressed a preference for this fork to have a clean commit-per-feature history over upstream rayon. Here, I'll meet you partway:

https://github.com/rayon-rs/rayon/compare/master...cuviper:rayon:rustc-0.5

Please check that I didn't mess that up... then would you like to revamp the TLV patch in that series? If so, feel free to rebase/rewrite the commit series as you see fit.

**Comment by Zoxc** [comment]
I merged the commits and included this PR. [Here's the branch](https://github.com/Zoxc/rayon/tree/rustc).

I also tested that rustc still works with it and looked over the commits.

**Comment by cuviper** [comment]
> I merged the commits and included this PR. [Here's the branch](https://github.com/Zoxc/rayon/tree/rustc).

Thanks! I further tweaked this to add `[lib] name` back to the regular names, so CI actually works without renaming every use. That should let you drop the dependency renaming in the rust repo too. I've force-pushed this to the `rustc` branch here, so if you're happy with that I'll publish it. I'll also update `indexmap` for 0.5.

**Comment by Zoxc** [comment]
Yeah, that looks fine.

**Comment by cuviper** [comment]
Published, should be all set!

**Pull request closed without merging**
